### Get all customers through api-docs 
GET http://localhost:8080/api-docs HTTP/1.1 

### Get customer by _id 
GET http://localhost:8080/api-docs/6334c6ef4e80bb90e8a5ce9c HTTP/1.1

### Add new customer
POST http://localhost:8080/api-docs HTTP/1.1

content-type: application/json

{
    "firstName": "Justin Michael",
    "lastName": "Jenkins",
    "address": "778 E Main St, Beech Island, SC",
    "birthDate": "July 7, 1970",
    "email": "justinmikes@fulfill.net",
    "classesTaken": "",
    "ordersPlaced": "",
    "subscribed": "No"
    }

### Update painter
PUT http://localhost:8080/api-docs/6329c369d876ca3c2783bea HTTP/1.1

content-type: application/json

{
    "firstName": "Justin Michael",
    "lastName": "Jenkins",
    "address": "778 E Main St, Beech Island, SC",
    "birthDate": "July 7, 1970",
    "email": "justinmikes@fulfill.net",
    "classesTaken": "",
    "ordersPlaced": "",
    "subscribed": "Yes"
}

### DELETE painter 
DELETE http://localhost:8080/api-docs/632f1fb793bc53fbef3c7047 HTTP/1.1

### Same requests on render 
GET https://painters-ui6d.onrender.com/api-docs HTTP/1.1

### GET by _id on Render 
GET http://https://painters-ui6d.onrender.com/api-docs/6329c369d876ca3c2783bea9 HTTP/1.1
 
### Add new customer 
POST http://painters-ui6d.onrender.com/api-docs HTTP/1.1

content-type: application/json

{
    "firstName": "Justin Michael",
    "lastName": "Jenkins",
    "address": "778 E Main St, Beech Island, SC",
    "birthDate": "July 7, 1970",
    "email": "justinmikes@fulfill.net",
    "classesTaken": "",
    "ordersPlaced": "",
    "subscribed": "Yes"
}

### Update customer
PUT http://painters-ui6d.onrender.com/api-docs/6329c369d876ca3c2783bea HTTP/1.1

content-type: application/json

{
    "firstName": "Justin Michael",
    "lastName": "Jenkins",
    "address": "778 E Main St, Beech Island, SC",
    "birthDate": "July 7, 1970",
    "email": "justinmikes@fulfill.net",
    "classesTaken": "",
    "ordersPlaced": "",
    "subscribed": "No"
}

### DELETE painter 
DELETE http://painters-ui6d.onrender.com/api-docs/632f1fb793bc53fbef3c7047 HTTP/1.1

### Get all classes through api-docs 
GET http://localhost:8080/api-docs HTTP/1.1
  
### Get classes by _id 
GET http://localhost:8080/api-docs/6334cf464e80bb90e8a5cea3 HTTP/1.1

### Add new class
POST http://localhost:8080/api-docs HTTP/1.1
content-type: application/json

{
    "className": "Master Muses: Monet Workshop",
    "classDate": "Every Friday in August",
    "classTime": "10 AM - 12 PM",
    "classLevel": "Intermediate",
    "suppliesIncluded": "No"
}
